language: python

# required to install gss-ntlmssp
sudo: true

# Most Python's support Xenial now, except 2.6, 3.4, and 3.5
dist: xenial

matrix:
  include:
  - python: 2.6
    dist: trusty
  - python: 2.7
  - python: 3.4
    dist: trusty
  - python: 3.5
    dist: trusty
  - python: 3.6
  - python: 3.7
  - python: 3.8-dev

before_install:
# install gss-ntlmssp required for tests
- sudo ./build-scripts/install_gssntlmssp.sh
install:
- pip install --upgrade pip setuptools
- pip install -r requirements-test.txt
- pip install .
- pip install coveralls

script:
- py.test -v --instafail --pep8 --cov pypsrp --cov-report term-missing

after_success:
- coveralls
