import enum
import typing

class GssChannelBindings:
    def __init__(
        self,
        initiator_addrtype: enum.IntEnum = enum.IntEnum(0),
        initiator_address: typing.Optional[bytes] = None,
        acceptor_addrtype: enum.IntEnum = enum.IntEnum(0),
        acceptor_address: typing.Optional[bytes] = None,
        application_data: typing.Optional[bytes] = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def pack(self) -> bytes: ...
    @staticmethod
    def unpack(b_data: bytes) -> "GssChannelBindings": ...
